import sqlite3
conn=sqlite3.connect("database.db")
cursor=conn.cursor()
questions=[
    (1,"What will be the output of the following code snippet? a = 5 b = 2 print(a // b)","2.5","2","2.0","2.00",2,"easy"),
    (1,"What is the output of the following code? value = 2 + 3 * 4 / 2 print(value)","4.5","10.0","8.0","12.0",3,"easy"),
    (1,"What is the purpose of the __dict__ attribute in Python?","To access the dictionary of a list","To store the attributes of an object","To define a dictionary in Python","To convert a dictionary to a list",2,"easy"),
    (1,"How do you create a dictionary using a comprehension in Python?","{key: value for key, value in iterable}","dict(iterable)","create_dict(iterable)","{key, value in iterable}",1,"easy"),
    (1,"How do you convert a floating-point number to an integer in Python?","int(number)","float_to_int(number)","number.int()","convert(int, number)",1,"easy"),
    (1,"Which of these is not a core data type?","Lists","Dictionary","Tuples","Class",4,"easy"),
    (1,"What is the purpose of the if statement in Python?","To define a function","To declare a variable","To execute a block of code conditionally","To create a loop",3,"easy"),
    (1,"Which of the following operators is used for equality comparison in Python?","==","=","===",">",1,"easy"),
    (1,"What will be the output of the following code snippet? x = 5 if x > 0: print(Positive') else:print('Negative')","Positive","Negative","Zero","Error",1,"easy"),
    (1,"How do you represent the logical AND operator in Python?","&&","and","AND","&",2,"easy"),
    (1,"How can you iterate over the items of a list using a while loop?","Use a for loop instead","Use the range function with the length of the list","Convert the list to a set and iterate over it.","Use the enumerate function",2,"medium"),
    (1,"In Python, can a while loop be used to iterate over a dictionary directly?","Yes","No","Only if the dictionary keys are integers","Only if the dictionary has a single key",1,"medium"),
    (1,"In Python, how can you emulate the behavior of a break statement inside a while loop without using bre","Use a return statement","Use a pass statement","Raise a custom exception","Use a goto statement",3,"medium"),
    (1,"In Python, can a while loop have multiple else blocks?","Yes","No","Only if the loop has multiple conditions","Only if the loop uses nested if statements",2,"medium"),
    (1,"What is the purpose of the assert statement in a while loop?","To terminate the loop","To check if a condition is true and raise an error if not","To skip the rest of the code in the loop","It is not a valid statement in a while loop",2,"medium"),
    (1,"What is the purpose of the else clause in a while loop?","It always runs after the loop completes","It is used to handle exceptions within the loop","It runs if the loop encounters an error","It runs if the loop completes without encountering a break statement",4,"medium"),
    (1,"How does the while-else construct work in Python?","It is not a valid construct in Python","The else block always runs after the loop","The else block runs if the loop encounters an error","The else block runs if the loop completes without encountering a break statement",4,"medium"),
    (1,"What is the purpose of the continue statement in a while loop?","Terminates the loop","Skips the remaining code in the loop and moves to the next iteration","Exits the loop prematurely","Breaks out of the loop entirely",2,"medium"),
    (1,"What is the output of the following Python code?num = 2 while num < 10: print(num, end=" ") num **= 2","Prints powers of 2 from 2 to 8","Prints the square of numbers from 2 to 10","Prints numbers in the range [2, 10) with a step of 2","Raises a SyntaxError",1,"medium"),
    (1,"What is the basic syntax of a while loop in Python?","while (condition):","for condition:","while loop condition do:","loop while condition:",1,"medium"),
    (1,"Which method is used to return the current position of the file cursor?","file.position()","get_cursor_position()","file.tell()","cursor_location()",3,"hard"),
    (1,"How do you copy the content of one file to another in Python?","copy_file()","file.copy()","shutil.copyfile()","copy_to()",3,"hard"),
    (1,"What does the 'a+b' mode stand for in file opening?","Append and Binary","Access and Backup","Append and Backup","Access and Binary",1,"hard"),
    (1,"Which method is used to move the cursor to a specific position in a file?","file.seek()","move_cursor()","cursor_position()","set_position()",1,"hard"),
    (1,"How do you check if a file is writable in Python?","file.writable()","os.path.writable()","os.access(file, os.W_OK)","file.is_writable()",3,"hard"),
    (1,"Which of the following code snippets opens a file named 'example.txt' in write mode and writes 'Hello, World!' to it?","file.write('Hello, World!')","with open('example.txt', 'w') as file: file.write('Hello, World!')","open('example.txt', 'w').write('Hello, World!')","open('example.txt', 'r').write('Hello, World!')",2,"hard"),
    (1,"What does the following code snippet do? with open('file.txt', 'a') as file: file.write('New data')","Reads the content of 'file.txt'","Appends 'New data' to 'file.txt'","Creates a new file 'file.txt'","Replaces the content of 'file.txt' with 'New data'",2,"hard"),
    (1,"What is file handling in Python?","Managing folders","Reading and writing file","Controlling system files","Handling exceptions in files",2,"hard"),
    (1,"How can you write data to a file without overwriting its existing content in Python?","Open the file with mode 'w' and call write()","Open the file with mode 'a' and call write()","Use file.write_append()","Use file.write('a')",3,"hard"),
    (1,"How do you read a file line by line in Python?","read_all_lines()","file.read_line()","readlines()","read_line(file)",3,"hard"),
    (2,"Which of the following is NOT a Feature of Java?","Platform independence","Object-oriented","Dynamically typed language","Robust",3,"easy"),
    (2,"Which component is responsible for converting bytecode to machine code?","Java Compiler","JDK","JVM","JRE",3,"easy"),
    (2,"Which part of the JDK is used to run Java programs?","javac","JRE","Javadoc","JAR",2,"easy"),
    (2,"Java code is compiled into which intermediate form?","Assembly","Bytecode","Binary","Machine code",2,"easy"),
    (2,"Which Java feature ensures code written once can run anywhere?","Platform independence","Multithreading","Security","Performance",1,"easy"),
    (2,"What is the result of true && false || true && true?","true","false","Compilation Error","Runtime Error",1,"easy"),
    (2,"Which operator has the highest precedence in Java?","+ (Addition)","&& (Logical AND)","* (Multiplication)","= (Assignment)",3,"easy"),
    (2,"Which operator is used for addition in Java?","+","++","+=","&",1,"easy"),
    (2,"What is the result of 7 % 3 in Java?","2","1","0","3",2,"easy"),
    (2,"Which class is commonly used for taking console input in Java?","FileReader","Scanner","PrintWriter","StringReader",2,"easy"),
    (2,"Which of the following is NOT an OOP concept in Java?","Encapsulation","Inheritance","Polymorphism","Compilation",4,"medium"),
    (2,"What is an object in Java?","A class template","An instance of a class","A function","A primitive data type",2,"medium"),
    (2,"Which keyword is used to create an object in Java?","class","this","new","void",3,"medium"),
    (2,"What is a class in Java?","A data type","A blueprint for objects","A collection of methods","A single method",2,"medium"),
    (2,"What is the correct way to define a class in Java?","public Example {}","class Example {}","void Example {}","object Example {}",2,"medium"),
    (2,"What does this keyword refer to?","Current object","Parent class","Static method","Return type",1,"medium"),
    (2,"Which keyword refers to the immediate parent class object?","base","super","parent","this",2,"medium"),
    (2,"Which of the following is true about Java constructors?","Constructors have a return type of void","Constructors must always be public","A constructor is automatically called when an object is created","Constructors can only be defined explicitly",3,"medium"),
    (2,"What happens if you do not define a constructor in a Java class?","The program will not compile","The compiler provides a default constructor","The class cannot be instantiated","The constructor from another class will be used",2,"medium"),
    (2,"Can a Java constructor be private?","No, it must be public","Yes, but the class cannot be instantiated outside the class","Yes, and it can be accessed from anywhere","No, Java does not allow private constructors",2,"medium"),
    (2,"Which package contains the File class in Java?","java.io.file","java.file","java.io","java.nio.file",3,"hard"),
    (2,"Which Hibernate method is used to insert/save a new object into the database?","update()","merge()","save()","delete()",3,"hard"),
    (2,"In Hibernate, which method is used to remove an object (entity) from the database?","remove()","delete()","evict()","detach()",2,"hard"),
    (2,"What is the purpose of the createNewFile() method in the File class?","To open an existing file","To create a new directory","To create a new file if it does not exist","To delete a file",3,"hard"),
    (2,"What will file.exists() return if the file doesn’t exist?","true","false","null","Throws Exception",2,"hard"),
    (2,"Which of the following can read text from a file line-by-line in Java?","FileWriter","BufferedWriter","Scanner","PrintWriter",3,"hard"),
    (2,"What is the output of this code? File f = new File('demo.txt'); System.out.println(f.isDirectory()); Assume demo.txt is a file, not a folder","true","false","null","Compilation Error",2,"hard"),
    (2,"Which method is used to get the size of a file in bytes?","getSize()","getLength()","length()","size()",3,"hard"),
    (2,"What does delete() method of the File class return when deletion fails?","Throws an exception","Returns false","Returns null","Returns the file name",2,"hard"),
    (2,"What is the correct way to create a directory in Java?","File.mkdir()","File.createDirectory()","File.createDir()","File.makeDirectory()",1,"hard"),
    (3,"What does DBMS stand for?","Data Backup Management System","Database Management System","Data Binary Management System","Database Backup Management System",2,"easy"),
    (3,"Which key uniquely identifies a record in a table?","Foreign Key","Primary Key","Composite Key","Candidate Key",2,"easy"),
    (3,"Which language is used to interact with databases?","HTML","SQL","Python","C++",2,"easy"),
    (3,"Which SQL command is used to retrieve data?","INSERT","SELECT","UPDATE","DELETE",2,"easy"),
    (3,"Which normal form removes partial dependency?","1NF","2NF","3NF","BCNF",2,"easy"),
    (3,"Which clause is used to filter records in SQL?","GROUP BY","ORDER BY","WHERE","HAVING",3,"easy"),
    (3,"Which SQL statement is used to delete a table?","REMOVE TABLE","DELETE TABLE","DROP TABLE","CLEAR TABLE",3,"easy"),
    (3,"Which of the following is a DML command?","CREATE","ALTER","INSERT","DROP",3,"easy"),
    (3,"Which constraint ensures no duplicate values?","NOT NULL","UNIQUE","CHECK","DEFAULT",2,"easy"),
    (3,"Which symbol is used for single-line comments in SQL?","//","--","#","/* */",2,"easy"),
    (3,"Which normal form eliminates transitive dependency?","1NF","2NF","3NF","4NF",3,"medium"),
    (3,"What is a foreign key used for?","Store duplicate data","Link two tables","Encrypt data","Delete records",2,"medium"),
    (3,"Which join returns only matching records from both tables?","LEFT JOIN","RIGHT JOIN","INNER JOIN","FULL JOIN",3,"medium"),
    (3,"What is ACID property in DBMS?","A database model","Transaction properties","Backup technique","Indexing method",2,"medium"),
    (3,"Which SQL function is used to count rows?","SUM()","COUNT()","TOTAL()","NUMBER()",2,"medium"),
    (3,"Which indexing structure is commonly used in databases?","Binary Tree","B+ Tree","Heap","Stack",2,"medium"),
    (3,"Which clause is used with aggregate functions?","WHERE","ORDER BY","HAVING","LIMIT",3,"medium"),
    (3,"What does ER model stand for?","Entity Relation","Entity Relationship","Entry Relation","Extended Relation",2,"medium"),
    (3,"Which command is used to modify existing table structure?","UPDATE","ALTER","MODIFY","CHANGE",2,"medium"),
    (3,"Which isolation level prevents dirty reads?","Read Uncommitted","Read Committed","Repeatable Read","Serializable",2,"medium"),
    (3,"Which normal form deals with multivalued dependency?","3NF","BCNF","4NF","5NF",3,"hard"),
    (3,"What is a deadlock in DBMS?","Data duplication","Infinite loop","Transactions waiting for each other","Database crash",3,"hard"),
    (3,"Which join returns all records from both tables including non-matching ones?","INNER JOIN","LEFT JOIN","RIGHT JOIN","FULL OUTER JOIN",4,"hard"),
    (3,"Which recovery technique uses log files?","Shadow Paging","Log-Based Recovery","Checkpointing","Rollback",2,"hard"),
    (3,"Which normal form removes join dependency?","3NF","4NF","5NF","BCNF",3,"hard"),
    (3,"Which index type improves range query performance?","Hash Index","B+ Tree Index","Bitmap Index","Clustered Index",2,"hard"),
    (3,"What is phantom read problem?","Reading uncommitted data","Row appears in repeated query","Data duplication","Transaction abort",2,"hard"),
    (3,"Which scheduling technique ensures serializability?","FIFO","Round Robin","Two-Phase Locking","Multilevel Queue",3,"hard"),
    (3,"Which SQL constraint enforces referential integrity?","PRIMARY KEY","FOREIGN KEY","UNIQUE","NOT NULL",2,"hard"),
    (3,"Which database architecture separates client and server?","1-tier","2-tier","3-tier","4-tier",3,"hard"),
    (4,"What is 20% of 150?","20","25","30","35",3,"easy"),
    (4,"If a train travels 60 km in 1 hour, what is its speed?","60 km/h","30 km/h","90 km/h","120 km/h",1,"easy"),
    (4,"What is the average of 10, 20, 30?","15","20","25","30",2,"easy"),
    (4,"What is 15 + 25 × 2?","80","65","55","70",2,"easy"),
    (4,"If 5 pens cost 50 rupees, what is cost of 1 pen?","5","8","10","12",3,"easy"),
    (4,"Find the next number: 2, 4, 6, 8, ?","9","10","12","11",2,"easy"),
    (4,"What is square of 12?","124","144","121","112",2,"easy"),
    (4,"If a number is divisible by 2 and 3, it must be divisible by?","5","6","4","9",2,"easy"),
    (4,"What is 100 ÷ 4?","20","25","30","40",2,"easy"),
    (4,"Find the simple interest on 1000 at 10% for 1 year.","50","100","150","200",2,"easy"),
    (4,"A man walks 5 km north then 5 km south. Where is he now?","5 km north","5 km south","Starting point","10 km away",3,"medium"),
    (4,"If ratio of A:B is 2:3 and A=20, what is B?","25","30","35","40",2,"medium"),
    (4,"What is compound interest on 1000 at 10% for 2 years?","200","210","220","230",2,"medium"),
    (4,"If 8 men can complete work in 10 days, how many days for 4 men?","5","10","20","15",3,"medium"),
    (4,"Find next: 3, 6, 12, 24, ?","36","48","60","72",2,"medium"),
    (4,"A train 100m long crosses pole in 10 sec. Speed?","10 m/s","5 m/s","15 m/s","20 m/s",1,"medium"),
    (4,"If CP=500 and SP=550, profit%?","5%","10%","15%","20%",2,"medium"),
    (4,"What is LCM of 12 and 18?","24","36","48","72",2,"medium"),
    (4,"A number increased by 20% becomes 120. Original?","80","90","100","110",3,"medium"),
    (4,"Probability of getting head in coin toss?","0","1","0.5","2",3,"medium"),
    (4,"A train crosses platform in 20 sec and pole in 10 sec. Ratio of train to platform length?","1:1","1:2","2:1","3:2",3,"hard"),
    (4,"If 15 workers do job in 8 days, how many workers for 4 days?","20","25","30","35",3,"hard"),
    (4,"What is the value of 3^4 + 4^3?","145","125","175","100",1,"hard"),
    (4,"If A can do work in 10 days and B in 15 days, together?","5 days","6 days","7 days","8 days",2,"hard"),
    (4,"Find next: 1, 4, 9, 16, 25, ?","30","35","36","49",3,"hard"),
    (4,"A sum doubles in 5 years at simple interest. Rate?","10%","20%","25%","15%",2,"hard"),
    (4,"If 2x + 3 = 15, value of x?","5","6","7","4",2,"hard"),
    (4,"Area of circle with radius 7? (π=22/7)","144","154","164","174",2,"hard"),
    (4,"Boat speed 10 km/h, stream 2 km/h. Downstream speed?","8","10","12","14",3,"hard"),
    (4,"Probability of rolling 3 in dice?","1/3","1/6","1/2","1/12",2,"hard"),
    (5,"Which tag is used to create hyperlink?","<a>","<link>","<href>","<url>",1,"easy"),
    (5,"Which property sets text color in CSS?","font-color","color","text-style","background-color",2,"easy"),
    (5,"Which tag is used for image?","<img>","<image>","<src>","<picture>",1,"easy"),
    (5,"Which HTML tag creates a paragraph?","<p>","<para>","<text>","<h1>",1,"easy"),
    (5,"Which CSS property changes background color?","bgcolor","background","background-color","color",3,"easy"),
    (5,"Which attribute specifies image source?","href","src","link","path",2,"easy"),
    (5,"Which tag creates unordered list?","<ul>","<ol>","<li>","<list>",1,"easy"),
    (5,"Which CSS property sets font size?","font-style","font-weight","font-size","text-size",3,"easy"),
    (5,"Which tag defines table row?","<td>","<tr>","<th>","<row>",2,"easy"),
    (5,"Inline CSS is written inside?","<css>","<style>","style attribute","<link>",3,"easy"),
    (5,"Which CSS property is used for flex layout?","display:flex","position:flex","float:flex","layout:flex",1,"medium"),
    (5,"Which tag is semantic?","<div>","<span>","<section>","<font>",3,"medium"),
    (5,"Which CSS position value removes element from normal flow?","static","relative","absolute","fixed",3,"medium"),
    (5,"Which unit is relative?","px","cm","%","pt",3,"medium"),
    (5,"Which tag is used for form input?","<form>","<input>","<button>","<submit>",2,"medium"),
    (5,"Which CSS property controls overflow?","display","overflow","float","clear",2,"medium"),
    (5,"Which selector selects all elements?","*",".","all","#",1,"medium"),
    (5,"Which property makes text bold?","font-style","font-weight","text-bold","style",2,"medium"),
    (5,"Which HTML5 tag is used for navigation?","<nav>","<menu>","<navigate>","<header>",1,"medium"),
    (5,"Which property is used to center text?","align","text-align","center-text","font-align",2,"medium"),
    (5,"Which CSS property creates stacking order?","z-index","stack","layer","order",1,"hard"),
    (5,"Which layout system is one-dimensional?","Grid","Flexbox","Float","Table",2,"hard"),
    (5,"Which pseudo-class selects first child?","::first","::first-child",":first-child",":child",3,"hard"),
    (5,"Which property is used for media queries?","@media","@query","@screen","@responsive",1,"hard"),
    (5,"Which CSS property prevents element shrinking in flexbox?","flex-grow","flex-basis","flex-shrink","flex-wrap",3,"hard"),
    (5,"Which attribute improves accessibility for images?","alt","title","aria","role",1,"hard"),
    (5,"Which property defines grid columns?","grid-template-columns","grid-columns","column-template","template-grid",1,"hard"),
    (5,"Which box model property adds space inside border?","margin","padding","border","outline",2,"hard"),
    (5,"Which selector targets element with id?","#",".","*","$",1,"hard"),
    (5,"Which CSS property makes element responsive width?","width:100px","width:100%","width:auto","display:block",2,"hard")
]
cursor.executemany("""
INSERT OR IGNORE INTO questiontable
(category_id, question, option1, option2, option3, option4, correct_option, difficulty)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
""", questions)

cursor.execute("SELECT COUNT(*) FROM questiontable")
cursor.fetchone()
conn.commit()
conn.close()
print("succesfully")